"""Build the isolated BKI embed from the existing website UI. No dependencies."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
assets = root / 'public' / 'assets'
page = (root / 'public' / 'index.html').read_text(encoding='utf-8')
fragment = page[page.index('    <section class="chat"'):page.index('    <script')]
svg_styles = re.findall(r'<style>(.*?)</style>', fragment, re.S)
fragment = re.sub(r'<style>.*?</style>', '', fragment, flags=re.S)
css = (assets / 'style.css').read_text(encoding='utf-8')
css = css.replace(':root', ':host').replace('body {', ':host {')
css = css.replace('.chat-is-open .chat-launcher', ':host(.chat-is-open) .chat-launcher')
css = css.replace('.chat-is-open { overflow: hidden; }', '')
css += '\n' + '\n'.join(svg_styles)
css += '\n:host { all: initial; display: block; position: fixed; width: 0; height: 0; right: 0; bottom: 0; z-index: 10000; font: 16px system-ui, sans-serif; color: #1f2937; }\n'
css += ':host([hidden]) { display: none; }\n'
js = (assets / 'chat.js').read_text(encoding='utf-8')
js = js.replace('(function () {', 'function mountChat(root, host, endpoint) {', 1)
assert js.rstrip().endswith('})();')
js = js.rstrip()[:-5] + '}\n'
js = js.replace('document.getElementById(', 'root.getElementById(')
js = js.replace('document.querySelectorAll(', 'root.querySelectorAll(')
js = js.replace("document.body.classList.toggle('chat-is-open', open)", "host.classList.toggle('chat-is-open', open)")
js = js.replace("fetch('api/chat.php', {", 'fetch(endpoint, {')
js = js.replace("method: 'POST', headers:", "method: 'POST', credentials: 'same-origin', headers:")
loader = '''
// This module is served from the same origin as the embedding BKI page.
const base = new URL('../', import.meta.url);
async function install() {
    if (base.origin !== location.origin) {
        throw new Error('HERMAESTRO benötigt einen Pfad unter derselben Origin wie die Website.');
    }
    if (document.getElementById('bki-hermaestro')) return;
    const host = document.createElement('div');
    host.id = 'bki-hermaestro';
    document.body.appendChild(host);
    const root = host.attachShadow({mode: 'open'});
    try {
        const stylesheet = document.createElement('link');
        stylesheet.rel = 'stylesheet';
        stylesheet.href = new URL('assets/embed.css', base).href;
        const stylesReady = new Promise((resolve, reject) => {
            stylesheet.onload = resolve;
            stylesheet.onerror = () => reject(new Error('Widget-CSS konnte nicht geladen werden.'));
        });
        root.appendChild(stylesheet);
        const response = await fetch(new URL('assets/embed.html', base), {credentials: 'same-origin'});
        if (!response.ok) throw new Error('Widget-HTML konnte nicht geladen werden.');
        // Trusted, application-owned static markup; never insert model text here.
        const template = document.createElement('template');
        template.innerHTML = await response.text();
        template.content.querySelectorAll('img[src]').forEach(img => {
            img.src = new URL(img.getAttribute('src'), base).href;
        });
        await stylesReady;
        root.appendChild(template.content);
        mountChat(root, host, new URL('api/chat.php', base).href);
    } catch (error) {
        host.remove();
        throw error;
    }
}
install().catch(error => console.error('HERMAESTRO konnte nicht gestartet werden.', error));
'''
(assets / 'embed.html').write_text(fragment, encoding='utf-8')
(assets / 'embed.css').write_text(css, encoding='utf-8')
(assets / 'embed.js').write_text('// Generated by tools/build_embed.py; do not edit directly.\n' + js + loader, encoding='utf-8')
print('Created public/assets/embed.html, embed.css and embed.js')
